version: '3.8'

services:
  client-dev:
    container_name: meou-client
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - REACT_APP_SERVER_URL=http://localhost:3004
    volumes:
      - ./client/src:/app/src
    networks:
      - meounet

  nginx:
    image: nginx:1.21.5-alpine
    container_name: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - client-dev
    networks:
      - meounet

networks:
  meounet:
