name: Publish Docker Image

on:
  push:
    branches: [main]
  release:
    types:
      - published

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DCR_PASSWORD }}

      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: docker.io/faisallarai/meou-client
          tag-sha: true
          tag-edge: false
          tag-latest: true

      - name: Build image
        uses: docker/build-push-action@v2
        with:
          tags: ${{ steps.docker_meta_api.outputs.tags }}
          file: ./Dockerfile

      - name: Push image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          file: ./Dockerfile
